const SHOP_DATA = [
  {
    title: "soccer",
    items: [
      {
        featuresList: [
          "REGULAR FIT",
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "FIRM GROUND OUTSOLE",
          "GREAT TRACTION ON THE FIELD",
          "LACE CLOSURE",
          "TEXTILE LINING",
        ],
        shoesList: [
          {
            id: 10,
            brandName: "Adidas",
            productName: "Predator Edge 3 Turf Soccer Cleats",
            subheader: "Iconic Shoes For Less",
            discountPrice: 69,
            originalPrice: 89,
            imageUrl: "https://i.ibb.co/rdDhCDN/adidas-soccer-shoe1.png",
            color: "Core / Black Carbon",
            starRating: 4.0,
            totalReviews: 2391,
          },
          {
            id: 12,
            brandName: "Nike",
            productName: "Nike Air Max 1 FB",
            subheader: "Iconic Shoes For Less",
            discountPrice: 109,
            originalPrice: 129,
            imageUrl: "https://i.ibb.co/n77rSV3/nike-airmax-soccer-shoe1.png",
            color: "Racer Blue / Summit White",
            starRating: 4.5,
            totalReviews: 3021,
          },
          {
            id: 13,
            brandName: "Hummel",
            productName: "Hummel Soccer Shoe",
            subheader: "Iconic Shoes For Less",
            discountPrice: 109,
            originalPrice: 139,
            imageUrl: "https://i.ibb.co/VHtGyd7/hummel-soccer-shoe1.png",
            color: "Neon Yellow / Lucid Blue",
            starRating: 5.0,
            totalReviews: 1823,
          },
        ],
      },
    ],
  },
  {
    title: "basketball",
    items: [
      {
        featuresList: [
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "PREMIUM INSOLES FOR SHOCK ABSORPTION & COMFORT",
          "RUBBER OUTSOLE FOR ADDED TRACTION",
          "STRUCTURED FIT & ICONIC LOOK",
          "PERCISE FIT TO PREVENT SLIPPING",
          "ANKLE SUPPORT",
        ],
        shoesList: [
          {
            id: 21,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 219,
            imageUrl: "https://i.ibb.co/K2XYLv5/nike-shoe-white.png",
            color: "Summit White / Black",
            starRating: 5.0,
            totalReviews: 5483,
          },
          {
            id: 22,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro High",
            subheader: "Iconic Shoes For Less",
            discountPrice: 159,
            originalPrice: 199,
            imageUrl: "https://i.ibb.co/8YGr16n/nike-shoe-red.png",
            color: "CARBON BLACK / CRIMSON",
            starRating: 4.0,
            totalReviews: 1458,
          },
          {
            id: 23,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 109,
            originalPrice: 129,
            imageUrl: "https://i.ibb.co/vqwjgd6/nike-shoe-green.png",
            color: "Summit White / Green / Cement Grey",
            starRating: 4.5,
            totalReviews: 1983,
          },
          {
            id: 24,
            brandName: "Air Jordan",
            productName: "Air Jordan 12 Retro",
            subheader: "Iconic Shoes For Less",
            discountPrice: 110,
            originalPrice: 140,
            imageUrl: "https://i.ibb.co/dmwMTTr/air-jordan12-gymred-basketball.png",
            color: "Gym Red",
            starRating: 5.0,
            totalReviews: 1763,
          },
        ],
      },
    ],
  },
  {
    title: "outdoor",
    items: [
      {
        featuresList: [
          "WATERPROOF MEMBRANE SEALS OUT WATER & LETS MOISTURE ESCAPE",
          "PROTECTIVE & ABRASION RESISTANT RUBBER HEEL AND TOE CAP",
          "PREMIUM LEATHER & PADDED COLLAR",
          "AIR CUSHION IN THE HEEL ABSORBS SHOCK & ADDS STABILITY",
          "PERCISE FIT TO PREVENT SLIPPING",
          "CUSTOM OUTSOLE PROVIDES EXCEPTIONAL TRACTION",
        ],
        shoesList: [
          {
            id: 31,
            brandName: "Merrell",
            productName: "Moab 3 Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 129,
            originalPrice: 159,
            imageUrl: "https://i.ibb.co/dW34jVY/hiking-shoe2.png",
            color: "Brown",
            starRating: 4.0,
            totalReviews: 836,
          },
          {
            id: 32,
            brandName: "Salomon",
            productName: "x Ultra 4 Mid Gore-Tex",
            subheader: "Iconic Shoes For Less",
            discountPrice: 139,
            originalPrice: 174,
            imageUrl: "https://i.ibb.co/w6QK23K/hiking-shoe3.png",
            color: "Dark Brown",
            starRating: 3.0,
            totalReviews: 432,
          },
          {
            id: 33,
            brandName: "Salomon",
            productName: "Quest 4 Gore-Tex",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 229,
            imageUrl: "https://i.ibb.co/xqDFCv8/hiking-shoe1.png",
            color: "Brown / Black",
            starRating: 4.5,
            totalReviews: 539,
          },
        ],
      },
    ],
  },
  {
    title: "work",
    items: [
      {
        featuresList: [
          "PREMIUM HAZEL HIGHWAY LEATHER",
          "PADDED COLLAR FOR A COMFORTABLE FIT AROUND THE ANKLE",
          "STEEL SHANK FOR ARCH SUPPORT",
          "SEAM-SEALED WATERPROOF",
          "TIMBERLAND PRO RUBBER LUG OUTSOLE FOR TRACTION",
          "STEEL SAFETY TOE",
        ],
        shoesList: [
          {
            id: 41,
            brandName: "Timberland",
            productName: "Timberland Premium 45th Anniversary 6 Inch Boot",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 199,
            imageUrl: "https://i.ibb.co/2jJhym2/leather-work-shoe3.png",
            color: "Brown",
            starRating: 5.0,
            totalReviews: 8768,
          },
          {
            id: 42,
            brandName: "Timberland",
            productName: "Timberland 6-Inch Premium Waterproof Boot",
            subheader: "Iconic Shoes For Less",
            discountPrice: 109,
            originalPrice: 130,
            imageUrl: "https://i.ibb.co/FgStBj0/timberland-work-shoe1.png",
            color: "Brown",
            starRating: 4.0,
            totalReviews: 4322,
          },
          {
            id: 43,
            brandName: "Timberland",
            productName: "Timberland 6-Inch Premium Boot",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/yFpRV7G/brown-leather-work-shoe2.png",
            color: "Dark Brown Full Grain",
            starRating: 3.5,
            totalReviews: 842,
          },
        ],
      },
    ],
  },
  {
    title: "casual",
    items: [
      {
        featuresList: [
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "COMFORTABLE FIT FOR EXTENDED EVERYDAY USE",
          "DESIGNED FOR DURABILITY & FUNCTIONALITY",
          "DURABLE MATERIALS FOR LONG-LASTING COMFORT",
          "HIGHLY BREATHABLE & SUPPORTIVE RUBBER OUTSOLE",
          "PERCISE FIT TO PREVENT SLIPPING",
        ],
        shoesList: [
          {
            id: 51,
            brandName: "Nike",
            productName: "React Infinity 3",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 199,
            imageUrl: "https://i.ibb.co/dc68qsL/colorful-shoe-casual.png",
            color: "Dark Smoke Grey",
            starRating: 5.0,
            totalReviews: 4532,
          },
          {
            id: 52,
            brandName: "Vans",
            productName: "Vans Old Skool Shoes",
            subheader: "Iconic Shoes For Less",
            discountPrice: 50,
            originalPrice: 70,
            imageUrl: "https://i.ibb.co/N6jdHy5/red-converse-shoe-casual.png",
            color: "Dark Crimson",
            starRating: 4.0,
            totalReviews: 3862,
          },
          {
            id: 53,
            brandName: "Nike",
            productName: "Nike Low Retro Shoes",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/Fxz9FQy/nike-low-casual.png",
            color: "Summit White / Black",
            starRating: 4.5,
            totalReviews: 2342,
          },
          {
            id: 54,
            brandName: "Nike",
            productName: "Nike Low Retro Shoes",
            subheader: "Iconic Shoes For Less",
            discountPrice: 109,
            originalPrice: 129,
            imageUrl: "https://i.ibb.co/k0fSbFC/brown-nike-casual.png",
            color: "Brown / Black",
            starRating: 3.5,
            totalReviews: 1203,
          },
          {
            id: 55,
            brandName: "New Balance",
            productName: "574 Low-Top Sneakers",
            subheader: "Iconic Shoes For Less",
            discountPrice: 59,
            originalPrice: 89,
            imageUrl: "https://i.ibb.co/SfG1cpY/pink-newbalance-shoe-casual.png",
            color: "Light Pink / Summit White",
            starRating: 3.0,
            totalReviews: 763,
          },
        ],
      },
    ],
  },
];

export default SHOP_DATA;
