const SHOP_DATA = [
  {
    title: "soccer",
    items: [
      {
        featuresList: [
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "GREAT TRACTION ON THE FIELD",
          "RUBBER OUTSOLE FOR ADDED TRACTION",
          "STRUCTURED FIT & ICONIC LOOK",
          "PERCISE FIT TO PREVENT SLIPPING",
          "ANKLE SUPPORT",
        ],
        shoesList: [
          {
            id: 10,
            brandName: "Adidas",
            productName: "Predator Edge 3 Turf Soccer Cleats",
            subheader: "Iconic Shoes For Less",
            discountPrice: 72,
            originalPrice: 90,
            imageUrl: "https://i.ibb.co/rdDhCDN/adidas-soccer-shoe1.png",
          },
          {
            id: 12,
            brandName: "Nike",
            productName: "Nike Air Max Soccer Shoes",
            subheader: "Iconic Shoes For Less",
            discountPrice: 159,
            originalPrice: 200,
            imageUrl: "https://i.ibb.co/n77rSV3/nike-airmax-soccer-shoe1.png",
          },
          {
            id: 13,
            brandName: "Hummel",
            productName: "Hummel Soccer Shoe",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/VHtGyd7/hummel-soccer-shoe1.png",
          },
        ],
      },
    ],
  },
  {
    title: "basketball",
    items: [
      {
        featuresList: [
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "PREMIUM INSOLES FOR SHOCK ABSORPTION & COMFORT",
          "RUBBER OUTSOLE FOR ADDED TRACTION",
          "STRUCTURED FIT & ICONIC LOOK",
          "PERCISE FIT TO PREVENT SLIPPING",
          "ANKLE SUPPORT",
        ],
        shoesList: [
          {
            id: 21,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 219,
            imageUrl: "https://i.ibb.co/K2XYLv5/nike-shoe-white.png",
          },
          {
            id: 22,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro High",
            subheader: "Iconic Shoes For Less",
            discountPrice: 159,
            originalPrice: 199,
            imageUrl: "https://i.ibb.co/8YGr16n/nike-shoe-red.png",
          },
          {
            id: 23,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/vqwjgd6/nike-shoe-green.png",
          },
          {
            id: 24,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro High",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 219,
            imageUrl: "https://i.ibb.co/dmwMTTr/air-jordan12-gymred-basketball.png",
          },
        ],
      },
    ],
  },
  {
    title: "outdoor",
    items: [
      {
        featuresList: [
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "PREMIUM INSOLES FOR SHOCK ABSORPTION & COMFORT",
          "RUBBER OUTSOLE FOR ADDED TRACTION",
          "STRUCTURED FIT & ICONIC LOOK",
          "PERCISE FIT TO PREVENT SLIPPING",
          "ANKLE SUPPORT",
        ],
        shoesList: [
          {
            id: 31,
            brandName: "Hiking",
            productName: "EDIT PRODUCT NAME",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 220,
            imageUrl: "https://i.ibb.co/dW34jVY/hiking-shoe2.png",
          },
          {
            id: 32,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro High",
            subheader: "Iconic Shoes For Less",
            discountPrice: 159,
            originalPrice: 199,
            imageUrl: "https://i.ibb.co/w6QK23K/hiking-shoe3.png",
          },
          {
            id: 33,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/xqDFCv8/hiking-shoe1.png",
          },
        ],
      },
    ],
  },
  {
    title: "work",
    items: [
      {
        featuresList: [
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "PREMIUM INSOLES FOR SHOCK ABSORPTION & COMFORT",
          "RUBBER OUTSOLE FOR ADDED TRACTION",
          "STRUCTURED FIT & ICONIC LOOK",
          "PERCISE FIT TO PREVENT SLIPPING",
          "ANKLE SUPPORT",
        ],
        shoesList: [
          {
            id: 41,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 220,
            imageUrl: "https://i.ibb.co/2jJhym2/leather-work-shoe3.png",
          },
          {
            id: 42,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro High",
            subheader: "Iconic Shoes For Less",
            discountPrice: 159,
            originalPrice: 199,
            imageUrl: "https://i.ibb.co/FgStBj0/timberland-work-shoe1.png",
          },
          {
            id: 43,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/yFpRV7G/brown-leather-work-shoe2.png",
          },
        ],
      },
    ],
  },
  {
    title: "casual",
    items: [
      {
        featuresList: [
          "PREMIUM LIGHTWEIGHT MATERIALS",
          "PREMIUM INSOLES FOR SHOCK ABSORPTION & COMFORT",
          "RUBBER OUTSOLE FOR ADDED TRACTION",
          "STRUCTURED FIT & ICONIC LOOK",
          "PERCISE FIT TO PREVENT SLIPPING",
          "ANKLE SUPPORT",
        ],
        shoesList: [
          {
            id: 51,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 179,
            originalPrice: 220,
            imageUrl: "https://i.ibb.co/dc68qsL/colorful-shoe-casual.png",
          },
          {
            id: 52,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro High",
            subheader: "Iconic Shoes For Less",
            discountPrice: 159,
            originalPrice: 199,
            imageUrl: "https://i.ibb.co/N6jdHy5/red-converse-shoe-casual.png",
          },
          {
            id: 53,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/Fxz9FQy/nike-low-casual.png",
          },
          {
            id: 53,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/k0fSbFC/brown-nike-casual.png",
          },
          {
            id: 53,
            brandName: "Air Jordan",
            productName: "Air Jordan 1 Retro Mid",
            subheader: "Iconic Shoes For Less",
            discountPrice: 149,
            originalPrice: 189,
            imageUrl: "https://i.ibb.co/SfG1cpY/pink-newbalance-shoe-casual.png",
          },
        ],
      },
    ],
  },
];

export default SHOP_DATA;
